---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Maliha Qayyum"
date: "September 18, 2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
library(Lahman)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has \_3015\_\_ observations and \_48\_\_ variables.

```{r}
install.packages("tidyverse")
```

```{r}
library(tidyverse)
```

```{r}
library(Lahman)
dim(Teams)
```

```{r}
install.packages("Lahman")
```

```{r}
?Teams
```

```{r}
dplyr::glimpse(Teams |> head())
```

### Exercise 2

...

```{r}
library(magrittr)
mets <- Teams  |> 
  dplyr::filter(teamID == "NYN")
my_mets <- mets |> 
  dplyr::filter(yearID %in% 2004:2012)|> 
  dplyr::select(yearID,G,W,L)
my_mets
```

### Exercise 3

...

```{r}
mets_ben <- Teams |>
  dplyr::select(teamID, yearID, G, RA, W, L, RS = R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

### Exercise 4

...

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = W / (W+L))
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct_hat * (W + L))
mets_ben
```

```{r}
mets_ben <- mets_ben %>% 
  mutate(WPct_hat = 1 / (1 + (RA/RS)^2))
mets_ben
```

### Exercise 5

```{r}
filter(mets_ben, W >= W_hat)
```

```{r}
filter(mets_ben, W >= W_hat)
```

```{r}
filter(mets_ben, W < W_hat)
```

...

### Exercise 6

...

```{r}
dplyr::arrange(mets_ben, desc(WPct))
```

### Exercise 7

...

```{r}
mets_ben %>% 
  dplyr::mutate(Diff = W - W_hat) |>
  dplyr::arrange(desc(Diff))
```

### Exercise 8

...

```{r}
mets_ben |> 
  dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(W) / sum(W + L), 
    sum_resid = sum(W - W_hat)
  )
```

### Exercise 9

...

```{r}
{r glimpse-data}
dplyr::glimpse(ikea)
```

```{r}
ggplot(data = ikea_data, aes(x = width_column_name, y = price_column_name)) +
  geom_point() + 
  labs(
    x = "Width (inches)", 
    y = "Price ($)", 
    title = "Relationship between Width and Price of Ikea Furniture"
  )
```

### Exercise 10

...

```{r}
library(dplyr)
mets_ben <- mets_ben %>% 
  dplyr::mutate(
    gm = ifelse(
      yearID <= 2004, "Jim Duquette",
      ifelse(
        yearID >= 2005 & yearID <= 2010, "Omar Minaya",
        ifelse(
          yearID >= 2011 & yearID <= 2012, "Sandy Alderson",
          NA
        )
      )
    )
  ) # Used mutate function from dplyr package in R to add a new col to mets_ben #
mets_ben
```
